### PR TITLE
(fix) Fixing the sort for slugline in global search and monitoring.

### PR DESCRIPTION
**Pull request by mdhaman**

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by marwoodandrew** [comment]
:+1:

**Comment by ioanpocol** [comment]
Looks like the following e2e test is failing for real:

1) monitoring can order content
  Message:
    Failed: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator by.repeater("item in items")

**Comment by mdhaman** [comment]
thanks @ioanpocol. I will look at the e2e test.

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
