### PR TITLE
[NITF] [FORMATTER] use the new HTML to NITF converter

### PR DESCRIPTION
**Pull request by jerome-poisson**
SDNTB-280

/!\ this P.R. can't validate tests before https://github.com/superdesk/superdesk-core/pull/580 is merged

### CODE REVIEW

**Comment by naspeh** [comment]
This PR https://github.com/superdesk/superdesk-core/pull/580 is merged already, so now it should pass also, right?

**Comment by jerome-poisson** [comment]
@naspeh indeed, there is a error due to a change on core's P.R., I'm currently working on a fix.

**Comment by jerome-poisson** [comment]
@petrjasek @naspeh this new P.R. fixes the problem https://github.com/superdesk/superdesk-core/pull/586, it should be alright once merged.

**Comment by jerome-poisson** [comment]
hey @naspeh it's now fixed, can review so I can merge please? Thanks :)

**Comment by naspeh** [comment]
Sorry for a delay.

**Pull request merged**
