### PR TITLE
[SD-3031] Test for updates of images from Reuters causes media entrie…

### PR DESCRIPTION
**Pull request by marwoodandrew**
…s to become orphaned

This is dependent on the corresponding pull request against superdesk-core!

### CODE REVIEW

**Comment by plamut** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
:+1:  No fix in the code. Love this :heart:

**Comment by marwoodandrew** [comment]
Test successfully fails!!! The code is in the core!! The test relies on the Reuters fixture data which is none core. What's the answer?

**Comment by amagdas** [comment]
Please one more review: https://github.com/superdesk/superdesk-core/pull/2

**Comment by amagdas** [comment]
@marwoodandrew When we have a PR depending on core, it's good to link to it so people can review both :bow:

**Pull request merged**
