### PR TITLE
[SD-2490] Create a NewsML G2 Output Format

### PR DESCRIPTION
**Pull request by marwoodandrew**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
Looks good. It would be good if we can externalize `AAP_PROVIDER_ID` also.

**Comment by marwoodandrew** [comment]
Yes, I think it should become just PROVIDER_ID and move into the settings, there is nothing AAP specific in the formatter then.

**Comment by ioanpocol** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Pull request merged**
