### PR TITLE
fix(media icons): Icons appearing outside of items frame

### PR DESCRIPTION
**Pull request by pavlovicnemanja92**
SD-2343

### CODE REVIEW

**Comment by plamut** [comment]
An e2e test for the existence of the `copy` and the `duplicate` icons is [broken](https://travis-ci.org/superdesk/superdesk/jobs/64058629#L1154), it needs to be updated.

**Comment by ioanpocol** [comment]
Running "jshint:all" (jshint) task

   app/scripts/superdesk-dashboard/workspace-tasks/tasks.js

     93 |    function fetch() {

                      ^ 'fetch' is defined but never used.

**Comment by plamut** [comment]
Where does this come from, the `tasks.js` file was not modified in this particular PR?

**Comment by ioanpocol** [comment]
There are a few PR with the same issue. Petr is working on it, so after it is fixed we can run the test again.

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
