### PR TITLE
SDPA-256 : PA Image API search activation

### PR DESCRIPTION
**Pull request by naomiaro**
should be setup by the pre-populate script

### CODE REVIEW

**Comment by hlmnrmr** [comment]
:+1:

**Comment by actionless** [comment]
ping me after merging in order to set those env vars in the deployment scripts

**Comment by actionless** [comment]
btw, who knows those credentials? @hlmnrmr @ioanpocol ?

**Comment by ioanpocol** [comment]
@actionless I sent you the credentials by email

**Comment by actionless** [comment]
added that env var

**Pull request merged**
