### PR TITLE
feat(publish): Added new subscriber type "both"

### PR DESCRIPTION
**Pull request by eozan**

### CODE REVIEW

**Comment by plamut** [comment]
:+1:
I assume the empty value of `subscriber.subscriber_type` is interpreted as "any of the two types", right?

**Comment by eozan** [comment]
that interpretation will be done on server, but yes, I think that's the idea.

**Comment by eozan** [comment]
(Failing tests are already fixed in https://github.com/superdesk/superdesk/pull/410)

**Comment by plamut** [comment]
OK, good, just wanted to make sure.

**Comment by amagdas** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Pull request merged**
