### PR TITLE
Keep embeds refs in ninjs associations [SDPA-155]

### PR DESCRIPTION
**Pull request by vied12**
References are stored in `associations` like:
```
"_embedded_8964700761":{"_created":"2016-02-18T13:58:37+0000","_etag":"c31b3ed93c4afbc424671a0905fb7fbfa553b770","_id":"56c5ce0d91e3ff00ac9bf9ce","_links":{"self":{"href":"picture_crop/56c5ce0d91e3ff00ac9bf9ce","title":"Picture_crop"}},"_status":"OK","_updated":"2016-02-18T13:58:37+0000","crop":{"CropBottom":720,"CropLeft":0,"CropRight":960,"CropTop":0},"height":720,"href":"http://localhost:5000/api/upload/56c5ce0d91e3ff00ac9bf9ce/raw?_schema=http","item":{"_created":"2016-02-18T11:03:02+0000","_current_version":2,"_etag":"28cfa2aa288aefdcdfc41514bafb341eaae7666e","_id":"urn:newsml:localhost:2016-02-18T11:03:02.406621:d8ec9999-0531-4f9c-8a8b-e71c04035159","_links":{"self":{"href":"/archive/urn:newsml:localhost:2016-02-18T11:03:02.406621:d8ec9999-0531-4f9c-8a8b-e71c04035159","title":"Archive"}},"_type":"archive","_updated":"2016-02-18T11:03:02+0000","byline":"DE","container":"location:workspace","dateline":{"date":"2016-02-18T11:03:02+0000","located":null,"source":"SAP","text":null},"description_text":"vvv","event_id":"tag:localhost:2016:a88340a5-e17b-47ff-a498-d937d3bfe2e9","expiry":"2016-03-19T11:03:02+0000","family_id":"urn:newsml:localhost:2016-02-18T11:03:02.406621:d8ec9999-0531-4f9c-8a8b-e71c04035159","filemeta":{"length":68311},"firstcreated":"2016-02-18T11:03:02+0000","guid":"tag:localhost:2016:0e037519-1345-4bde-8355-c2b1a3267e5c","headline":"viande","language":"en","marked_for_not_publication":false,"media":"56c5a4e691e3ff00ac9bf95d","mimetype":"image/jpeg","more_coming":false,"operation":"update","original_creator":"56af54d924d8a7001bc586dc","place":[],"priority":6,"pubstatus":"usable","renditions":{"baseImage":{"height":1050,"href":"http://localhost:5000/api/upload/56c5a4e691e3ff00ac9bf961/raw?_schema=http","media":"56c5a4e691e3ff00ac9bf961","mimetype":"image/jpeg","width":1400},"original":{"height":720,"href":"http://localhost:5000/api/upload/56c5a4e691e3ff00ac9bf95d/raw?_schema=http","media":"56c5a4e691e3ff00ac9bf95d","mimetype":"image/jpeg","width":960},"thumbnail":{"height":120,"href":"http://localhost:5000/api/upload/56c5a4e691e3ff00a .... }
```
Comments look like:
```
<!-- EMBED START Image {id: "_embedded_8964700761"} --><figure><img alt="vvv" src="http://localhost:5000/api/upload/56c5ce6291e3ff00ac9bf9d4/raw?_schema=http"><figcaption>vvv</figcaption></figure><!-- EMBED END Image {id: "_embedded_8964700761"} -->
```

### CODE REVIEW

**Comment by petrjasek** [comment]
:+1:

**Comment by actionless** [comment]
:+1:

**Comment by pavlovicnemanja** [comment]
:+1:

**Comment by ph0bos** [comment]
perhaps better align to the NinJS spec where possible (e.g. _updated = “versioncreated”, _created = “firstcreated” etc

**Pull request merged**
