### PR TITLE
fix(bamboo): use environment for db config

### PR DESCRIPTION
**Pull request by petrjasek**
on bamboo there is no db on localhost, it's configured via environment.

refactored #804 
@sivakuna-aap

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
Looks good. We are doing the same thing in `settings.py` also. So, can we move `get_mongo_uri()` to settings.py and reuse the function in both `settings.py` and `tests.py`?

**Comment by amagdas** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Comment by petrjasek** [comment]
@sivakuna-aap we don't change the name there we just read it from env

**Pull request merged**
