### PR TITLE
[SD-4048] - Generic macro command

### PR DESCRIPTION
**Pull request by akintolga**

### CODE REVIEW

**Comment by akintolga** [comment]
@petrjasek Macro files appear in both superdesk and superdesk-core. Was that because we need to preserve the relative location of the folder to load them dynamically?

**Comment by akintolga** [comment]
Depends on: https://github.com/superdesk/superdesk-core/pull/168

**Comment by petrjasek** [comment]
right I've removed this in https://github.com/superdesk/superdesk/pull/1757

**Comment by akintolga** [comment]
This is not needed anymore.

**Pull request closed without merging**
