### PR TITLE
fix(authoring):some metadata fields are not saved/updated(handled locate...

### PR DESCRIPTION
**Pull request by sjunaid**
...d,

dateline,language fields similar to others)

sd-1605

### CODE REVIEW

**Comment by petrjasek** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by ioanpocol** [comment]
rebase is needed

**Comment by ioanpocol** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
