### PR TITLE
SD-3438

### PR DESCRIPTION
**Pull request by darconny**
Improvements od modal windows

### CODE REVIEW

**Comment by pavlovicnemanja** [comment]
:+1:

**Comment by Aca-jov** [comment]
:+1:

**Comment by plamut** [comment]
@darconny This change broke the routing schedule edit modal, could you please have a look? Thanks!
I am also attaching a screenshot for the reference:

broken_modal

**Comment by akintolga** [comment]
Please see PR: https://github.com/superdesk/superdesk/pull/1280

On Wed, Oct 21, 2015 at 11:06 AM, Peter Lamut <notifications@github.com>
wrote:

> @darconny <https://github.com/darconny> This change broke the routing
> schedule edit modal, could you please have a look? Thanks!
> I am also attaching a screenshot for the reference:
>
> [image: broken_modal]
> <https://cloud.githubusercontent.com/assets/1235663/10624394/a686854c-77e3-11e5-88e6-32911de652b8.jpeg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/superdesk/superdesk/pull/1275#issuecomment-149740107>.
>



-- 

*Tolga Akin | *Senior Analyst Programmer


*Australian Associated Press*
Level 5, 3 Rider Boulevard, Rhodes NSW 2138, Australia
PO Box 3411, Rhodes NSW 2138, Australia
*T *+61 2 9322 8598  *F *+61 2 9322 8086
takin@aap.com.au | www.aap.com.au

-- 
*This email may contain information that is confidential. If you receive an 
email in error please delete it immediately.*

**Pull request merged**
