### PR TITLE
(blocker) Fix locators reading on ubuntu

### PR DESCRIPTION
**Pull request by amagdas**
SD-2858 sd-test server is not working

### CODE REVIEW

**Comment by plamut** [comment]
Test is missing for the change, but good otherwise.

**Comment by amagdas** [comment]
There are a bunch of tests for this feature, this failed at runtime with celery, I don't really see the value in trying to add a test for this.

**Comment by plamut** [comment]
Hm, so there is no good way to reproduce this error in a test environment that would prove the issue (and the fix for it), if I understood correctly?

**Comment by amagdas** [comment]
Yup, that's the gist of it. Should I mention that I tested the fix directly on the test server? :imp:

**Comment by plamut** [comment]
Meh, then we'll have to live with it I guess...

:+1:

**Comment by sivakuna-aap** [comment]
:+1:

**Pull request merged**
