### PR TITLE
Fix css for modal windows

### PR DESCRIPTION
**Pull request by Aca-jov**

### CODE REVIEW

**Comment by plamut** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by vied12** [comment]
This PR reverts my PR https://github.com/superdesk/superdesk/pull/647.
Can I know what does it fix @Aca-jov ?

**Comment by Aca-jov** [comment]
We had broken modal windows (on adding widgets), and we lost scroll on modal windows (on window resize), so this css is needed after all...

**Comment by vied12** [comment]
And do you have any clue why it breaks our styles like https://github.com/superdesk/superdesk/pull/647#issue-81429753 ?

**Comment by Aca-jov** [comment]
No... Is this the only broken modal, or every modal is like this?

**Comment by vied12** [comment]
This is the only one we have.
here is the html http://pastie.org/private/cjtref5umqxdinwzjcneq
(from http://liveblog.sd-test.sourcefabric.org/#/liveblog on a "Create
Blog" click)

**Comment by Aca-jov** [comment]
You need to add width:100% in form, that will resolve width problem, but on window resize, there is scroll problem (scroll is not appearing), so compare our modals with yours and try to find why it works on superdesk and not on liveblog..

https://master.sd-test.sourcefabric.org on top right you have add widget button, clik there for modal.

**Pull request merged**
