### PR TITLE
fix(workspace): move links from top bar to side bar

### PR DESCRIPTION
**Pull request by petrjasek**
there are no icons for ingest/content, it's rotated text atm.
also changed css so when there is route with sidebar it handles
main container position instead of positioning ng-view contents.

SD-2788

### CODE REVIEW

**Comment by ioanpocol** [comment]
:+1:

**Comment by plamut** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
:+1: Can we add tooltips to the icons in sidenav? QA has raised an issues about the same. SD-2789

**Comment by petrjasek** [comment]
@sivakuna-aap will add it in a different PR, working on something related

**Comment by sivakuna-aap** [comment]
ok :+1:

**Pull request merged**
