### PR TITLE
(feat) [SD-1990] Publishing channel sequence numbering

### PR DESCRIPTION
**Pull request by sivakuna-aap**

### CODE REVIEW

**Comment by amagdas** [comment]
:+1:

**Comment by akintolga** [comment]
Siva, do we need to save the sequence number to the queue as well? What do you think?

**Comment by sivakuna-aap** [comment]
@akintolga is there any requirement which requires the sequence number in queue?

**Comment by akintolga** [comment]
I don't think so. But I'd say it would be a good check the see what numbers are assigned. A sanity check.

**Comment by sivakuna-aap** [comment]
Ok. I will add make the changes and update the pr

**Comment by sivakuna-aap** [comment]
Adding published sequence number to both publish_queue and formatted_item

**Comment by akintolga** [comment]
:+1:

**Comment by amagdas** [comment]
:+1:

**Pull request merged**
