### PR TITLE
(fix) [SD-3650] Page refreshing is required for vocabulary changes to take effect

### PR DESCRIPTION
**Pull request by sivakuna-aap**

### CODE REVIEW

**Comment by ioanpocol** [comment]
Is this change solving the need to refresh page issue?

**Comment by sivakuna-aap** [comment]
When a user updates the vocabulary it doesn't refresh the page. Instead displays notification saying the vocabulary has been updated. This is confirmed with POs. This PR fixes the notification display.

**Comment by ioanpocol** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
