### PR TITLE
SD-292: Create new version of a package - protractor tests

### PR DESCRIPTION
**Pull request by mugurrus**

### CODE REVIEW

**Comment by actionless** [comment]
@mugurrus firefox failure in e2e is ok

**Comment by ioanpocol** [comment]
:+1:

**Comment by amagdas** [comment]
Cherry-picked this changes to https://github.com/superdesk/superdesk/pull/108, I think we can close this.

**Comment by ioanpocol** [comment]
This is not fixed yet and there will be a lot some changes to fix it.

**Comment by amagdas** [comment]
The tests on firefox still fail, exactly as before, now the build passes as we ignore failures on firefox

**Comment by mugurrus** [comment]
The tests on FF fail because of bad driver, we agreed to ignore the FF tests run for now.

**Comment by amagdas** [comment]
I know, my point was this PR is only actually enabling back the test, the state is the same as before, works on Chrome and fails on FF, not sure the latest added changes are needed.

**Pull request merged**
