### PR TITLE
Search and Saved search fixes

### PR DESCRIPTION
**Pull request by akintolga**
[SD-2955]
[SD-3261]

This PR also changes the way the search is saved so when it is merged please remove all the existing saved searches from the system.

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by ioanpocol** [comment]
PR https://github.com/superdesk/superdesk/pull/1408 has fixed the e2e tests problems.
Please rebase.

**Comment by ioanpocol** [comment]
A few behave tests are failing:

Failing scenarios:
  features/saved_searches.feature:130  Create a Saved Search with invalid filter
  features/saved_searches.feature:165  Create a Saved Search and retrieve content
  features/saved_searches.feature:231  A user with global search privilege can update another user's search

**Pull request merged**
