### PR TITLE
Local demo

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by actionless** [comment]
i am not sure about moving vhost from docker to client or not

**Comment by petrjasek** [comment]
I think it would make sense to run single nginx as proxy for server and also serving client files, then it should be outside both client and server

**Comment by actionless** [comment]
@petrjasek but currently it's actually like that

**Comment by petrjasek** [comment]
ah right so then imo it shouldn't be part of client

**Comment by actionless** [comment]
so what is your idea, to swap dockerfiles back and make nginx-less Dockerfile default?

**Comment by petrjasek** [comment]
I'm not sure, we can keep it like this.

**Pull request closed without merging**
