### PR TITLE
feat(spelling): Warning message if there are spelling mistakes when sending item

### PR DESCRIPTION
**Pull request by pavlovicnemanja92**
SD-2154

### CODE REVIEW

**Comment by plamut** [comment]
Unit tests... :wink:

**Comment by ioanpocol** [comment]
:+1:  (an e2e test will help too)

**Comment by pavlovicnemanja92** [comment]
Maybe to create sub-task for tests?

**Comment by plamut** [comment]
Yeah, write both. :smile:

**Pull request closed without merging**
