### PR TITLE
[SD-2614] Add validators for picture and video items

### PR DESCRIPTION
**Pull request by marwoodandrew**
This PR will require that the validators collection be deleted and re-created using the command 

python manage.py app:initialize_data -n validators

### CODE REVIEW

**Comment by amagdas** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by amagdas** [comment]
Will merge this Monday morning when I will clean the master instance data as well.

**Comment by sivakuna-aap** [comment]
@amagdas  Don't clean the master instance until I submit the PR. It's a major change and will effect multiple collections.

**Comment by amagdas** [comment]
oky

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Pull request merged**
