### PR TITLE
Remove requirejs

### PR DESCRIPTION
**Pull request by thnkloud9**
objective is to remove requirejs dependency completely from superdesk client.

### CODE REVIEW

**Comment by petrjasek** [comment]
almost there!

**Comment by thnkloud9** [comment]
@petrjasek @vied12 @takeit - only 3 tests are still failing, and only two spec files.  My brain is a little fried and I can't seem to tackle these:

app/scripts/superdesk/auth/auth-service_spec.js
app/scripts/superdesk/auth/session-service_spec.js

If you have a few mins, please have a look.  I've commented them pretty heavily with "THIS FAILS"

**Comment by petrjasek** [comment]
:+1: and seems like you can remove `test-main` and `config` file, those were only used by require.

**Comment by takeit** [comment]
I just noticed that the `auth/auth-service_spec.js` has some tests not fixed yet (it is commented out). We will try to take a look into it today.

**Comment by thnkloud9** [comment]
auth/auth-service_spec.js tests have been updated, and test-main and config files have been removed.

**Comment by akintolga** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
