### PR TITLE
SDPA-264 : Change 'slugline' back to 'keyword' and place under 'topic'

### PR DESCRIPTION
**Pull request by naomiaro**

### CODE REVIEW

**Comment by petrjasek** [comment]
I think you have to also add `app-templates-cache.js` into index.html, it's not there yet. without this it won't work when you run grunt build

**Comment by naomiaro** [comment]
ah ok I'll try that, didn't see that this was failing.

**Comment by naomiaro** [comment]
<script src="templates-cache.js"></script>

this is currently in index.html

**Comment by petrjasek** [comment]
it gets created when you run grunt build. also app-templates-cache.js, and that's missing in index.html, should go after templates-cache.js. btw when you do grunt build it will create those files in dist folder

**Comment by vied12** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
