### PR TITLE
fix(bamboo): use MONGO_URI env and not MONGOLAB for config

### PR DESCRIPTION
**Pull request by petrjasek**
mongolab was used long time ago. no need to have 2 envs for mongo. error prone..

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1: that resolves the confusion.

**Comment by plamut** [comment]
Closed/reopened to re-run the Travis build, might have been a false positive (a timeout in one of the behave tests, seen that before).

**Comment by sivakuna-aap** [comment]
All tests pass this time :100: :blue_heart: :yellow_heart: :purple_heart:

**Comment by sivakuna-aap** [comment]
This time all tests pass :100:  :purple_heart: :yellow_heart: :blue_heart:

**Pull request merged**
