### PR TITLE
feat(publish) [SD-1549] Backend: Create a publish endpoint for publishing items.

### PR DESCRIPTION
**Pull request by sivakuna-aap**
Also a user shouldn't be allowed to update after publishing.
[SD-1545] Added a scenario for testing uniqueness of routing scheme names

### CODE REVIEW

**Comment by petrjasek** [comment]
I think it might be better to make publish a separate module.. archive gets a bit fat (and it shouldn't be archive anyhow)

**Comment by amagdas** [comment]
I agree with @petrjasek  :+1:

**Comment by sivakuna-aap** [comment]
Refactored publish endpoint to a new package

**Comment by amagdas** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
