### PR TITLE
(fix) [SD-3607] - Open button in the related items widget does not work for published items

### PR DESCRIPTION
**Pull request by sjunaid**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by ioanpocol** [comment]
Running "jshint:all" (jshint) task
   spec/helpers/authoring.js
    390 |    }
              ^ Missing semicolon.

**Comment by ioanpocol** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
