### PR TITLE
feat(spelling): Warning message if there are spelling mistakes when sending item

### PR DESCRIPTION
**Pull request by pavlovicnemanja92**
SD-2154

Closed previous pull request because of error while making synchronization.

https://github.com/superdesk/superdesk/pull/764

### CODE REVIEW

**Comment by pavlovicnemanja92** [comment]
https://github.com/superdesk/superdesk/pull/764

**Comment by ioanpocol** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Comment by amagdas** [comment]
:+1:

**Pull request merged**
