### PR TITLE
[sd-2293]-Killed item destination groups drop down should not be active(handled scheduler in the meta data be inactive in view mode)

### PR DESCRIPTION
**Pull request by sjunaid**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
Changes related to `Killed item destination groups drop down should not be active` are missing I guess. I see changes for disabling date and time pickers only.

**Comment by sjunaid** [comment]
Siva, that dropdown part was previously handled and merged in another ticket SD-2365.

**Comment by sivakuna-aap** [comment]
ok :+1:

**Comment by amagdas** [comment]
:+1:

**Pull request merged**
