### PR TITLE
(fix) Rebuild ngtemplates on html change.

### PR DESCRIPTION
**Pull request by mdhaman**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:  :+1:

**Comment by plamut** [comment]
:+1: :+1: :+1:

**Comment by marwoodandrew** [comment]
:+1: :+1: :+1: :+1:

**Comment by petrjasek** [comment]
@thnkloud9 does it still work for you without `templates.js` in repo? i guess we will have to push this into some extra bower repo

**Comment by thnkloud9** [comment]
@petrjasek - thanks for this update and your help.  No, this would not work for us at the moment.  But, maybe we could generate for tags (releases), or if we are planning on generating builds for releases, we can (and probably should) update our client to use minified dist/ includes?  This would also be much cleaner for vpp and liveblog I think, no?

**Comment by petrjasek** [comment]
@thnkloud9 check #1055

**Pull request merged**
