### PR TITLE
Fixed content templates issues

### PR DESCRIPTION
**Pull request by Aca-jov**
SD-3432

### CODE REVIEW

**Comment by plamut** [comment]
I would add a regression test as well.

**Comment by Aca-jov** [comment]
I don't need tests are needed, because I fixed some smaller bugs. I think this is too much going in details: test for checking if some button is disabled or if some options are selected/deselected.
Can someone else also give it a look?

**Comment by plamut** [comment]
I just thought maybe `$scope.validSchedule()` could be tested, although if fixes just revolve around enabling/disabling UI widgets, then we _might_ skip the tests. We generally don't test these indeed, though there were cases where similar small changes required a test, and others where bigger changes were merged without having one.

I won't oppose if the consensus is that a test is not needed here, as the changes themselves seem fine.
:+1:

**Comment by ioanpocol** [comment]
PR https://github.com/superdesk/superdesk/pull/1408 has fixed the e2e tests problems.
Please rebase.

**Pull request merged**
