### PR TITLE
[sd-3541]-(fix)- Fetch link causes faulty desk list

### PR DESCRIPTION
**Pull request by sjunaid**

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by ioanpocol** [comment]
PR https://github.com/superdesk/superdesk/pull/1408 has fixed the e2e tests problems.
Please rebase.

**Comment by mugurrus** [comment]
No need to rebase, the PR can be merged and passed all the tests.

**Comment by ioanpocol** [comment]
Will be just a test to see if the e2e fixes works well.

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
