### PR TITLE
SDPA-330 : Pull in metadata from image file for editing

### PR DESCRIPTION
**Pull request by naomiaro**

### CODE REVIEW

**Comment by ahilles107** [comment]
where exif.js is used?

**Comment by naomiaro** [comment]
@ahilles107 it's in client core which isn't merged yet

https://github.com/superdesk/superdesk-client-core/pull/177

**Comment by ahilles107** [comment]
@petrjasek this is where subsplit would help so much. Now you need to follow 2PR for one change (and one of them looks like invalid).

**Comment by naomiaro** [comment]
yeah I agree with this 2 PR thing being confusing, also I don't like how related changed can't be merged together.

**Comment by petrjasek** [comment]
I'm not sure how it would work with multiple clients, any ideas? because here it's client specific version

**Comment by ahilles107** [comment]
hmm... so it's only for AAP? It's not clear as it goes to `superdesk/superdesk` branch master. So it looks like default client + client core version.

**Comment by petrjasek** [comment]
this is pa's branch, will be eventually superdesk-pa repository

**Comment by naomiaro** [comment]
@petrjasek but if this library is being used in client core, it will need to be included in all client branches.

**Comment by petrjasek** [comment]
but we will update master too eventually

**Comment by petrjasek** [comment]
sure @naomiaro

**Comment by ahilles107** [comment]
ahh i missed that branch (hat to check it in othere PR). I have no idea how to organize subtrees with this case (many clients and one core). From my point of view it's totally wrong - as we will build separate app foe every client. But it's not connected to this PR.

**Comment by petrjasek** [comment]
yep exactly

**Pull request merged**
