### PR TITLE
refactor(server: apps: archive: common): use mongo instead of redis sequence for key generation

### PR DESCRIPTION
**Pull request by actionless**
follow-up on https://github.com/superdesk/superdesk/pull/1510

### CODE REVIEW

**Comment by actionless** [comment]
should i also got use of this?
http://docs.celeryproject.org/en/latest/getting-started/brokers/mongodb.html

**Comment by mugurrus** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Comment by petrjasek** [comment]
@actionless no, we will use rabbitMQ not mongo

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
