### PR TITLE
fix(rename label): Rename label for highlight items

### PR DESCRIPTION
**Pull request by pavlovicnemanja92**
SD-2228

### CODE REVIEW

**Comment by ioanpocol** [comment]
:+1:

**Comment by plamut** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
Tooltip of add item to highlight, for each item in list/grid view is "Mark Item" at present. The label of this tooltip should also change.

**Comment by ioanpocol** [comment]
This tooltip si about to create a new highlight package and not about to mark an item for a highlight.

**Pull request merged**
