### PR TITLE
(fix) Fixng the ingest provider create and update.

### PR DESCRIPTION
**Pull request by mdhaman**
These are the test for the following in the superdesk-core
https://github.com/superdesk/superdesk-core/pull/7

Will need the superdesk-core to be merged

### CODE REVIEW

**Comment by plamut** [comment]
:+1:

**Comment by amagdas** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by amagdas** [comment]
The version of superdesk-core needs to be updated.

**Comment by mdhaman** [comment]
@amagdas modified dependencies.

**Pull request merged**
