### PR TITLE
test(travis): set gunicorn timeout to 10s

### PR DESCRIPTION
**Pull request by petrjasek**
it should fail requests after 10s, so we should see where
ui is stuck waiting for server

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by ioanpocol** [comment]
PR https://github.com/superdesk/superdesk/pull/1408 has fixed the e2e tests problems.
Please rebase.

**Comment by ioanpocol** [comment]
is this PR still needed?

**Comment by petrjasek** [comment]
no

**Pull request closed without merging**
