### PR TITLE
fix(publish): add embedded flag to embedded validators

### PR DESCRIPTION
**Pull request by petrjasek**
it prevented publishing of embedded images together with text item.

### CODE REVIEW

**Comment by petrjasek** [comment]
ping @superdesk/superdesk-developers

**Comment by jerome-poisson** [comment]
:+1:

**Comment by pavlovicnemanja** [comment]
:+1:

**Comment by jerome-poisson** [comment]
@petrjasek can you also merge this on ntb branch ?

**Comment by petrjasek** [comment]
@jerome-poisson I don't see those embedded validators being used there, so it wouldn't do much there. any idea how it works there @ioanpocol ?

**Pull request merged**
