### PR TITLE
[SD-3324] Remove the update option if the item is re-written.

### PR DESCRIPTION
**Pull request by mdhaman**

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by plamut** [comment]
:+1:

**Comment by ioanpocol** [comment]
PR https://github.com/superdesk/superdesk/pull/1408 has fixed the e2e tests problems.
Please rebase.

**Comment by mdhaman** [comment]
@ioanpocol done that.

**Pull request merged**
