### PR TITLE
travis on content-api branch

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by plamut** [comment]
Can you please rebase onto the latest content-api branch? Because this contains a lot of things already merged in it. Thanks!

**Comment by actionless** [comment]
@plamut rebased

**Comment by plamut** [comment]
@actionless For some reason this PR still contains a lot of already merged commits in this PR. Did you try to rebase your 5773f2f commit --onto the content-api branch? It should be the only commit in this PR...

**Comment by actionless** [comment]
but it's directly committed to that branch

**Comment by plamut** [comment]
Yeah, it's just that it makes it a bit harder for others to review because your changes are mixed with the other already merged changes, thus the suggestion.

BTW, this is still WIP, right, and not yet  meant to be merged?

**Comment by actionless** [comment]
u can forcely push contents-api branch back instead of rebased one, i can create PR to it then

**Comment by petrjasek** [comment]
shouldn't this PR go to `content-api` branch?

**Comment by plamut** [comment]
Man, of course. :) I didn't even notice this was sent to master.

It's true, it should be sent to the content-api branch, yes.

**Pull request closed without merging**
