### PR TITLE
fix(desk dropdown): Added Untitled for workspace where name is not specified

### PR DESCRIPTION
**Pull request by pavlovicnemanja92**
There was some cases when workspace name is empty. This is a fix for it.

desk drodpown

### CODE REVIEW

**Comment by Aca-jov** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
Isn't Workspace name mandatory? If not I would suggest it to make mandatory.

**Comment by pavlovicnemanja92** [comment]
Yeah, it is mandatory... But there are some ways where workspace is created without name. I couldn't reproduce this, and because of that this is "just in case" fix :)

**Comment by mugurrus** [comment]
:+1:

**Comment by amagdas** [comment]
:+1:

**Pull request merged**
