### PR TITLE
Fix loading of all users, only the first 200 users were loaded

### PR DESCRIPTION
**Pull request by amagdas**
SD-2017  Add user to desk does not take

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
Is it a good idea to load all users into browser cache? Can't we use auto complete instead of loading at once?

**Comment by amagdas** [comment]
We have  a bunch of places where we depends on this behaviour, I agree that we should refactor this.
I will create a technical task to propose a fix.

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by amagdas** [comment]
@superdesk/developers @akintolga @marwoodandrew

**Comment by eozan** [comment]
I agree that it's not a good idea to do this as a permanent solution.
:+1:

**Pull request merged**
