### PR TITLE
fix(monitoring): SD-3612 Fixed monitoring widget responsive behavior

### PR DESCRIPTION
**Pull request by pavlovicnemanja**
SD-3612

### CODE REVIEW

**Comment by plamut** [comment]
:+1:

**Comment by plamut** [comment]
[offtopic] Wow, a build that passed, nice. :D

**Comment by pavlovicnemanja** [comment]
Restarted just three times :)

**Comment by sivakuna-aap** [comment]
:+1: Merging it before u kill someone :wink:

**Pull request merged**
