### PR TITLE
[NITF] [FORMATTER] fixed dateline element

### PR DESCRIPTION
**Pull request by jerome-poisson**
SDNTB-280

### CODE REVIEW

**Comment by petrjasek** [comment]
:+1: test would be great

**Comment by jerome-poisson** [comment]
@petr yes I was actually writting some

**Comment by jerome-poisson** [comment]
@petrjasek I've changed test to avoid formatting for each test, so if you can give a second look it would be great, thanks :)

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
