### PR TITLE
Fix (edit mode on double click)

### PR DESCRIPTION
**Pull request by Aca-jov**
SD-2653

### CODE REVIEW

**Comment by plamut** [comment]
Looks good (except for the missing test :laughing: )

**Comment by ioanpocol** [comment]
:+1:

**Comment by ioanpocol** [comment]
The following line on e2e test should be updated to check if the editor is on edit mode:
https://github.com/superdesk/superdesk/blob/master/client/spec/monitoring_spec.js#L176

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
