### PR TITLE
fix(styles): Responsive behaviour

### PR DESCRIPTION
**Pull request by fritzSF**
Changed the behaviour of panels on smaller screens:
- preview overlaps the editor
- aspect ratio of editor and list is changed in favor of the editor

### CODE REVIEW

**Comment by plamut** [comment]
:+1:

**Comment by amagdas** [comment]
:+1:

**Comment by pavlovicnemanja92** [comment]
:+1:

**Comment by ioanpocol** [comment]
Failures:
1) monitoring view can preview content
  Message:
    Expected '' to be 'item6'.
  Stack:
    Error: Failed expectation
        at Object.<anonymous> (/home/travis/build/superdesk/superdesk/client/spec/monitoring_spec.js:162:46)

**Comment by ioanpocol** [comment]
The issue is that when the screen is smaller the preview window is not showed. Because of this the 2e2 test fails, because the screen resolution on tests is smaller.
Also on double click the preview and edit are overlapping (see below image)

edit

**Comment by fritzSF** [comment]
We need this kind of behaviour on smaller screens, otherwise the list is to narrow and totally unusable

**Pull request merged**
