### PR TITLE
fix(templates): SD-3587 Impossible to save a new or edited template

### PR DESCRIPTION
**Pull request by ioanpocol**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by petrjasek** [comment]
imo would be good to have some test for this

**Comment by ioanpocol** [comment]
We need a e2e some tests on template add&edit. But for now I will skip the tests because there is no e2e test on templates and the next sprint the add/edit template will be reimplemented.

**Comment by petrjasek** [comment]
i ment unittest for deleting of that property if it prevents template from saving..

**Comment by ioanpocol** [comment]
I changed one of existing unittets

**Pull request merged**
