### PR TITLE
fix(aap image) remove the link to the aap one system in renditions

### PR DESCRIPTION
**Pull request by marwoodandrew**
The idea of serving aap images and videos from the AAP DC system is defunct, this pull request removes the additional link from renditions.

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by plamut** [comment]
:+1: 
(I assume this piece of code already as tests and they pass, right?)

**Comment by marwoodandrew** [comment]
The beauty of not having a test in the first place is when you remove the functionality you don't need to remove the test!

**Comment by plamut** [comment]
Haha, ok then. :)

**Comment by mdhaman** [comment]
:+1:

**Pull request merged**
