### PR TITLE
fix(client): make indentation consistent in js

### PR DESCRIPTION
**Pull request by petrjasek**
it's set to 4 spaces now
@superdesk/developers @sivakuna-aap @marwoodandrew @mdhaman @akintolga 
make sure your editors are set to expand tabs..

### CODE REVIEW

**Comment by plamut** [comment]
:-1: The linter is already doing it's job well, causing Travis to fail due to inconsistent indentation in some of the files. :)

**Comment by petrjasek** [comment]
ups :smile: can we get rid of it? :smiley:
i will have to update my npm

**Comment by plamut** [comment]
What do you mean? Is it because these not-a-multiple-of-four indentation errors are caused by some automated task?
If not, it seems trivial to fix the problematic files.

**Comment by petrjasek** [comment]
no I was using it when fixing locally, but didn't get those errors. after doing npm update I can see it

**Comment by plamut** [comment]
It's good now. :+1:

**Pull request merged**
