### PR TITLE
Publishing

### PR DESCRIPTION
**Pull request by akintolga**
- Settings for Destination Groups, Output Channels and Subscriptions
- Settings for ingest routing to include destination groups
- Assigning destination groups to articles
- Publishing an article
- Initial output format: NITF
- Initial transmissions: FTP, Email
- Publish queue implementation
- Celery tasks for transmitting articles using the publish queue

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1: behave tests are failing

**Comment by marwoodandrew** [comment]
:+1:

**Comment by amagdas** [comment]
:+1:

**Comment by amagdas** [comment]
There is a problem in authoring screen that we need to fix before merging.

**Comment by petrjasek** [comment]
I think it should be fixed by https://github.com/superdesk/superdesk/commit/b6e3d31f4905c257828bc9b3268c63b7b53303a2

**Comment by akintolga** [comment]
Thanks @petrjasek , that line looks like solved the problem in authoring.

**Comment by amagdas** [comment]
:100:

**Pull request merged**
