### PR TITLE
fix(authoring): Fixed rendition problem.

### PR DESCRIPTION
**Pull request by eozan**

### CODE REVIEW

**Comment by plamut** [comment]
IMO a regression test should be added as well, while the fix itself looks fine.

**Comment by petrjasek** [comment]
@eozan can you rebase or close this one? not sure it's a duplicate

**Comment by eozan** [comment]
Rebased. This fixes the "Cannot read property '4-3' of undefined" js error, but I'm not sure if it's the best way.

**Comment by ioanpocol** [comment]
:+1:

**Comment by petrjasek** [comment]
I don't understand how it's fixing the problem, seems identical to me. @eozan can you explain?

**Comment by eozan** [comment]
@petrjasek right, it's exactly identical. I will close this pr and check it again.

**Pull request closed without merging**
