### PR TITLE
fix(authoring): Fixed removing associations.

### PR DESCRIPTION
**Pull request by eozan**
SDPA-113

### CODE REVIEW

**Comment by petrjasek** [comment]
would it be possible to remove this without opening the modal?
like just adding a cross into top right corner in the preview?

**Comment by eozan** [comment]
possible, let's discuss this with @fritzSF

**Comment by vied12** [comment]
+1 for the cross ✖️

**Comment by eozan** [comment]
I'm closing this pull request as it wil be done from scratch. (Work needed is totally different for modal and cross solutions). Let's include important details like this in the task description next time.

**Pull request closed without merging**
