### PR TITLE
feat(editor): Added custom playbuzz embed.

### PR DESCRIPTION
**Pull request by eozan**
SDPA-64

### CODE REVIEW

**Comment by vied12** [comment]
:ok_hand:

**Comment by pavlovicnemanja** [comment]
:+1

**Comment by mugurrus** [comment]
I think it's not a good idea to tightly couple a functionality for a specific client in the superdesk repo. This should be as generic as possible. Even if it's in our repo it should be possible to enable/disable it.

**Comment by vied12** [comment]
of course we will put that in another module later. The SD client is not totally ready for that yet :grin:
I vote to merge it, and I will dissociate the specific code in another PR. Because what is here is not the only one! :bowtie:

**Comment by hlmnrmr** [comment]
:+1: 
... but yeah, let's not forget about this, @mugurrus is right and should be handled in a different way in the near future.

**Pull request merged**
