### PR TITLE
SD-1620 : Wrong error message when ingesting to personal

### PR DESCRIPTION
**Pull request by ioanpocol**
Added support to fetch into Personal

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by amagdas** [comment]
:+1:

**Comment by petrjasek** [comment]
I don't think it should be supported.. There is a requirement to prevent this.

**Comment by sivakuna-aap** [comment]
I agree with @petrjasek . The ticket is related to changing the error message language.

**Comment by ioanpocol** [comment]
The user is not allowed to fetch in personal space

**Pull request closed without merging**
