### PR TITLE
(fix) Updating superdesk-core dependency.

### PR DESCRIPTION
**Pull request by mdhaman**

### CODE REVIEW

**Comment by Michael-Gourlay** [comment]
Thanks Mayur. :he  Can we get this done on a regular basis - not necessarily for every merge to the core, but at least on a routine basis by one or the other team?

**Comment by mdhaman** [comment]
@Michael-Gourlay  I got lots of love. But no thumbs up :wink:

**Comment by Michael-Gourlay** [comment]
:+1:  :100:

**Comment by petrjasek** [comment]
:+1:

**Comment by plamut** [comment]
This lost me at least 3 hours yesterday, did not realize I was using the older core version... :/
Hence more :heart: from me, too. :laughing:

P.S.: :+1:

**Comment by sivakuna-aap** [comment]
Closing this as https://github.com/superdesk/superdesk/pull/1382 covers this.

**Pull request closed without merging**
