### PR TITLE
(fix)  Added/Modified validator definition for other content types

### PR DESCRIPTION
**Pull request by sivakuna-aap**
Resolves:
[SD-3460](https://dev.sourcefabric.org/browse/SD-3460) Header length being appropriate still gives an error before publish
[SD-3513](https://dev.sourcefabric.org/browse/SD-3513) Cannot kill or correct video items. Also, added/modified validator definition for other content types.

**Information to Mergers**
After merging, please drop validators collection and recreate from the `validators.json` file.

### CODE REVIEW

**Comment by mdhaman** [comment]
@sivakuna-aap adding video validator and changes to the validator for text items are fine. But have discussion with Lasky on media (picture/video) validator for the fields that are required.

**Comment by amagdas** [comment]
Is this done or WIP?

**Comment by marwoodandrew** [comment]
Done, I hope! It's basically just a couple of macros for routing rules. (except for DPA  where the macros is still called in the DPA Ingest service)

**Comment by sivakuna-aap** [comment]
I will verify with Lasky once tomorrow and will update if necessary. For time being am adding "wip" label

**Comment by sivakuna-aap** [comment]
@marwoodandrew I guess wrong window!!!

**Comment by sivakuna-aap** [comment]
Updated the PR after checking with Andrew Lasky.

**Comment by amagdas** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
ping @superdesk/developers

**Comment by mdhaman** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Pull request merged**
