### PR TITLE
Fix (comment and resize layout on locked items)

### PR DESCRIPTION
**Pull request by Aca-jov**
SD-3077

### CODE REVIEW

**Comment by pavlovicnemanja92** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
Needs rebasing.

**Comment by plamut** [comment]
:+1:

**Comment by amagdas** [comment]
:+1:

**Comment by plamut** [comment]
@Aca-jov Just for the reference - I _strongly_ encourage to write more descriptive commit messages, there are invaluable when tracing back any hidden bugs that might have been introduced awhile ago.

This pull request, on the other hand, contains seven commits with more than half of them saying simply "Fix". These things can backfire in the future, thus please pay more attention to that.

I would also recommend combining multiple commits with each containing only trivial (and related) changes into a single logical commit, since this, too, makes reviewing the commit history easier, if needed.

**Pull request merged**
