### PR TITLE
(fix) [SD-3609] - Introduce search by headline in publish queue

### PR DESCRIPTION
**Pull request by sjunaid**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
@sjunaid the requirement wasn't for case insensitive search. But for fuzzy search. Check how headline search works in Global Search. Since the publish queue entries aren't in elasticsearch this might be bit tricky.

**Comment by petrjasek** [comment]
maybe we can try using mongo text index and `$text` search operator here, but that would require some backend work (index setup).

**Comment by sjunaid** [comment]
@sivakuna-aap and @petrjasek , IMO, `$regex` operator sufficiently working for this case, i.e, serving for approximate string matching on headline field. or am i still missing something?

**Comment by sivakuna-aap** [comment]
I missed the `$regex`. Thanks for clarifying. :+1:

**Comment by akintolga** [comment]
LGTM :+1:

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
