### PR TITLE
refact(search) - Duplicate search parameters that exist in filters removed

### PR DESCRIPTION
**Pull request by akintolga**
- anpa_category, genre, priority and urgency exist in aggregations and they can be used from "Filters"

### CODE REVIEW

**Comment by akintolga** [comment]
pinging @ioanpocol

**Comment by akintolga** [comment]
depends on https://github.com/superdesk/superdesk-client-core/pull/903

**Comment by ioanpocol** [comment]
Even if those items appears on facets, NTB requested to have them on filters too. Probably Karel can show again the new refactored search to NTB and probably they will change their mind.

**Comment by akintolga** [comment]
@ioanpocol thanks for the response. 

When I was testing in https://ntb.dev.superdesk.org/#/ I noticed that the way those parameters work also different than the way that they work in filters. This affects the way the query and tags. 

I agree with you that they will probably change their mind, even if not this area needs to be revisited to make it similar to the filters.

**Comment by ioanpocol** [comment]
@akintolga At the moment we implemented it worked well, but I will check it again.

**Comment by akintolga** [comment]
Karel has approved these changes for NTB today.

**Comment by ioanpocol** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
