### PR TITLE
fix(docker): fix unittests for publicapi in docker

### PR DESCRIPTION
**Pull request by petrjasek**
it was missing config with prefix which works fine on localhost,
but not when mongo is running in a container

### CODE REVIEW

**Comment by plamut** [comment]
:+1: 

Just curious, though, why Docker environment is/was different from e.g. the Travis builds? Is it possible that some other things are different, too?

IIRC we've already had a few cases when things worked, but not when deployed with Docker due to some differences in the environment.

**Comment by petrjasek** [comment]
on travis you have mongo on `localhost` (and that's default setting so it was working), but in docker it's on mongodb container ip address so it has to read it from env

**Comment by plamut** [comment]
Ah, makes sense.

Are you perhaps aware of any other differences that might exist between our "localhost" builds and Docker builds? (we should bridge as much of these as possible)

**Comment by petrjasek** [comment]
afaik that should be it

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
