### PR TITLE
feat(user sessions): Selete user sessions

### PR DESCRIPTION
**Pull request by ioanpocol**
e2e tests will be in the next commit/PR.

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by amagdas** [comment]
I think it will be safer if we do this by disabling the user.
When disabling the user, we remove all the session and the user is no longer able to login/create a new session until the admin finishes with the role changes.

**Comment by sivakuna-aap** [comment]
If the intention behind this PR is the one mentioned by @amagdas then I do agree with what he says

**Comment by amagdas** [comment]
So until we clarify this: :-1:

**Comment by ioanpocol** [comment]
Per Andrew Lasky the disable user cover the close session functionality so I close this PR.

**Pull request closed without merging**
