### PR TITLE
feat(desk dropdown): Improvements for desk and workspace dropdowns

### PR DESCRIPTION
**Pull request by pavlovicnemanja92**
SD-2841

### CODE REVIEW

**Comment by plamut** [comment]
Tests and docstrings missing, but other than that it looks good to me.

**Comment by pavlovicnemanja92** [comment]
Tests for what? This was just UI change, I just add a variable to JS file, so I can add class according to selected type. All other is HTML/CSS change.

**Comment by plamut** [comment]
The tests for the `workspaceType` variable you added that the `WorkspaceDropdownDirective` directive manipulates in the scope methods it defines.

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by amagdas** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by plamut** [comment]
**@all:** please don't merge that just yet, tests are on the way.

**Pull request merged**
