### PR TITLE
Fix (disctionary issues)

### PR DESCRIPTION
**Pull request by Aca-jov**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by petrjasek** [comment]
is find&replace still working after this? it was using blur event to trigger update

**Comment by mdhaman** [comment]
undo/redo functionality was also using blur event. Is this working?

**Comment by Aca-jov** [comment]
I checked both find/replace and undo/redo is working without blur.

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
