### PR TITLE
Creating new item in personal workspace with selected desk fixed

### PR DESCRIPTION
**Pull request by Aca-jov**
SD-3838, SD-3901

### CODE REVIEW

**Comment by petrjasek** [comment]
can you write a test for this? it seems quite error prone so better to have this covered

**Comment by sivakuna-aap** [comment]
:+1: Agree with Petr

**Comment by ioanpocol** [comment]
Please rebase

**Comment by mugurrus** [comment]
Some JS unit tests and e2e tests crash.

**Comment by Aca-jov** [comment]
Test added and all fixed.

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
