### PR TITLE
[SD-1815] sanitise incomming html email

### PR DESCRIPTION
**Pull request by marwoodandrew**

### CODE REVIEW

**Comment by amagdas** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by plamut** [comment]
I know it's a latecomer, but this shouldn't have been merged just yet. I'll open a new ticket.

**Comment by marwoodandrew** [comment]
I'll have a look at it on Monday

**Comment by plamut** [comment]
Sure, no rush, enjoy your weekend! :wink:

**Comment by marwoodandrew** [comment]
Looks like it is stripping all attributes, I note that in the signature of one of the journo's the anchor tag has been stripped of the href! :-) (one problem solved!)

<a>www.aap.com.au</a>

**Comment by plamut** [comment]
Well yeah, that's exactly what I wrote here, all the attributes get removed - https://github.com/marwoodandrew/superdesk/commit/097328d524e567424effc84d13363bf26de7c4a4#commitcomment-10662117

**Comment by marwoodandrew** [comment]
Yep saw that!

**Pull request merged**
