### PR TITLE
[DOCKER] added grammalecte Dockerfile + added the service to docker-c…

### PR DESCRIPTION
**Pull request by jerome-poisson**
…ompose files

SDBELGA-131

### CODE REVIEW

**Comment by petrjasek** [comment]
shouldn't this be done on superdesk/superdesk-belga repo?

**Comment by jerome-poisson** [comment]
@petrjasek I think a French grammar/spellchecker is generally useful, not only for Belga.

**Comment by jerome-poisson** [comment]
@petrjasek so what shoudl I do? An other option is to keep the grammalecte Dockerfile here, but not adding it to `docker-compose-services.yml` nor `docker-compose.yml` , and only adding it for custom projects which need it (i.e. Belga).

**Comment by petrjasek** [comment]
sounds good :+1:

**Pull request merged**
