### PR TITLE
Make the currently edited routing scheme rule highlighted

### PR DESCRIPTION
**Pull request by plamut**
Resolves [SD-2434](https://dev.sourcefabric.org/browse/SD-2434).

Please see the attached screenshot for an idea how the change looks like. The currently selected filter has a dark gray background.

routing_scheme_edit

P.S.: We keep `client/bower/styles/css/bootstrap.css` under source control, right?

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1: I think deletion of `bootstrap.css` isn't needed

**Comment by plamut** [comment]
@sivakuna-aap It wasn't deleted, just recompiled and replaced with a new version. It seems that we have this file under source control, thus I didn't do any changes to `.gitignore`.

**Comment by sivakuna-aap** [comment]
ok..

**Comment by mdhaman** [comment]
:+1:

**Comment by amagdas** [comment]
:+1:

**Pull request merged**
