### PR TITLE
[sd-3947-1] - (fix upload part1) - Canceling upload the re-uploading …

### PR DESCRIPTION
**Pull request by sjunaid**
…does not activate the save button

### CODE REVIEW

**Comment by sjunaid** [comment]
This PR need to review and merge with https://github.com/superdesk/superdesk-client-core/pull/4

**Comment by petrjasek** [comment]
pls update core version in package.json to:
```
"dependencies": {"superdesk-core": "superdesk/superdesk-client-core#2fd824c"}
```

**Comment by petrjasek** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Pull request merged**
