### PR TITLE
fix(schema): use elastic that can handle dict mapping

### PR DESCRIPTION
**Pull request by petrjasek**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
We had an issue with elastic serializer. When null/none value is passed to a referenced property the serializer serializes it to some ObjectId value and checks if a document with that ObjectId exists in the referenced collection and eventually fails as there won't be any document with that object id. Not sure if this will reproduce that issue!!! We might need a test to check if null values gets converted to ObjectId or not.

**Comment by ioanpocol** [comment]
:+1:

**Comment by petrjasek** [comment]
@sivakuna-aap added a test, but not sure it matches the issue, what do you think?

**Comment by amagdas** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
@petrjasek I think the test you added should cover

**Pull request merged**
