### PR TITLE
Table in editor [SDNTB-101]

### PR DESCRIPTION
**Pull request by vied12**

### CODE REVIEW

**Comment by mugurrus** [comment]
You need to update e2e tests

**Comment by vied12** [comment]
@mugurrus I don't get why, I only added a button in the editor toolbar.
Does the errors in e2e tests can be related to the other changes in superdesk-client-core ?
https://github.com/superdesk/superdesk-client-core/compare/749f9de...903efb7

**Comment by mugurrus** [comment]
The errors happen on selection of certain GUI elements so you should check the corresponding tests and see what changed that broke the elements selection.

**Comment by vied12** [comment]
Actually even the base branch doesn't pass the test
https://travis-ci.org/superdesk/superdesk/builds/112006969

**Comment by ioanpocol** [comment]
@vied12  Please make the PR against ntb.
For core PRs please use master branches.
Sorry for late notice.

**Pull request closed without merging**
