### PR TITLE
new editor: editable caption for images SDPA-44

### PR DESCRIPTION
**Pull request by vied12**
Support for:
- [x] featured image caption
- [x] embedded image caption

### CODE REVIEW

**Comment by petrjasek** [comment]
:+1:

**Comment by vied12** [comment]
e2e 1 and 3 passed, but not the number 2. What does it mean ?

**Comment by petrjasek** [comment]
it means there is an error :smile:

**Comment by vied12** [comment]
haha ok but what is the difference between 1,2 and 3 ?

**Comment by petrjasek** [comment]
it's just splitted into 3 groups to run faster

**Comment by vied12** [comment]
I thought it was to give a chance for unstable tests to succeed at least one time ^^
Ok will see what I can do if they fail again

**Pull request merged**
