### PR TITLE
chore(npm): update npm dependencies

### PR DESCRIPTION
**Pull request by petrjasek**
highlights:
 - protractor 2.1 + using jasmine2 for tests

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
Build is failing because
> Collecting python3-ldap==0.9.7 (from -r requirements.txt (line 40))
> Could not find a version that satisfies the requirement python3-ldap==0.9.7 (from -r requirements.txt (line 40)) (from versions: 0.9.8.4)
Some externally hosted files were ignored as access to them may be unreliable (use --allow-external to allow).
No distributions matching the version for python3-ldap==0.9.7 (from -r requirements.txt (line 40))`

**Comment by sivakuna-aap** [comment]
Needs rebase

**Comment by ioanpocol** [comment]
:+1:

**Comment by amagdas** [comment]
I don't think that travis has the latest Chrome version...

**Comment by petrjasek** [comment]
i think it's jasmine2 vs jasmine1 issue

**Comment by amagdas** [comment]
Usually travis lags behind with browser versions, this has been a problem for quite some time...

**Comment by petrjasek** [comment]
@amagdas it's using chrome 45

**Comment by ioanpocol** [comment]
Only 2 tests are failing and one is pending, so seams to be OK. We have to investigate those 3 tests.

**Comment by petrjasek** [comment]
at last..

**Comment by amagdas** [comment]
:+1:

**Pull request merged**
