### PR TITLE
feat(client: ingest): expose provider id to scope

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
why is this required?

**Comment by actionless** [comment]
it is needed for third-party ingest provider i am working on

**Comment by sivakuna-aap** [comment]
OK. Is there a ticket for it? Wanted to understand what Third Party Ingest Provider is.

**Comment by actionless** [comment]
https://dev.sourcefabric.org/browse/CD3-2

https://github.com/actionless/superdesk/blob/citizendesk-wip/client/app/scripts/superdesk-feed-webhook/views/webhookRealConfig.html#L3

**Comment by mugurrus** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
