### PR TITLE
(fix) Modified the replacement words keys.

### PR DESCRIPTION
**Pull request by mdhaman**
depends on [PR-292](https://github.com/superdesk/superdesk-core/pull/292)
@actionless have to update the vocab after this get merged.

### CODE REVIEW

**Comment by marwoodandrew** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by mdhaman** [comment]
Merging this PR. 

@actionless  need to update the vocabularies.

**Pull request merged**
