### PR TITLE
feat(authoring): Implemented saving/loading state to aggregate widget.

### PR DESCRIPTION
**Pull request by eozan**
SD-2394

### CODE REVIEW

**Comment by plamut** [comment]
Tests are missing, the rest looks good to me.

**Comment by ioanpocol** [comment]
:+1:  (except e2e tests)

**Comment by plamut** [comment]
No, rather prefer unit tests. :wink: (the best of course is to have both)

The reason is behave tests are _slow_ and thus do not encourage running them repeatedly when you write code. Unit tests, on the other hand, run much quicker and give you feedback in a much more reasonable time. On top of that, they also point you to the exact part of the code that failed, making  it easier to locate bugs.

Both of the above-mentioned properties of unit tests are essential for efficient TDD.

**Comment by plamut** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
