### PR TITLE
fix(paimg): Change the url used for PA Images

### PR DESCRIPTION
**Pull request by ioanpocol**

### CODE REVIEW

**Comment by petrjasek** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Comment by petrjasek** [comment]
@ioanpocol any more work to be done here?

**Comment by ioanpocol** [comment]
I changed back to use 'search' endpoint. Tests are failing, so we have to update from master.

**Comment by petrjasek** [comment]
why switching back to `search` ?

**Comment by ioanpocol** [comment]
Ian asked on hipchat to switch back but to keep the 'ck' parameter. Now also on 'search' the response time is good.

**Comment by petrjasek** [comment]
I see :+1:

**Pull request merged**
