### PR TITLE
imp(global search): SD-3735 UI Improvement for saved search and eliminated minimize button

### PR DESCRIPTION
**Pull request by pavlovicnemanja**
- [x] SD-3636 Eliminate minimize button
- [x] SD-3735 UI Improvement for saved search

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
@pavlovicnemanja Looking at the code I think it also resolves https://dev.sourcefabric.org/browse/SD-3876. Can you cross check it once? If it's been taken care of then after merging please assign this ticket also QA Team.

**Comment by pavlovicnemanja** [comment]
@sivakuna-aap Yeah, It also fixed that issue! :)

**Comment by sivakuna-aap** [comment]
:+1:

**Pull request merged**
