### PR TITLE
Fix (spiked list): On double click should not open spiked item on edit mode

### PR DESCRIPTION
**Pull request by Aca-jov**
SD-3093

### CODE REVIEW

**Comment by plamut** [comment]
IMO an extra test case should be added to verify that editing only happens for non-spiked items, especially since the `edit()` method is complex enough to justify this.

A docstring welcome as well, even though it is "just" a helper function (the `scheduleQuery()` function has it, for instance).

The commit message itself is descriptive and serves the purpose.

**Comment by mugurrus** [comment]
Yep, needs a test. The edit function is pretty self-explanatory.

**Comment by amagdas** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
