### PR TITLE
templates module renamed to superdesk.templates-cache

### PR DESCRIPTION
**Pull request by vied12**
`templates` wasn't safe enough to prevent conflict with other dependencies

### CODE REVIEW

**Comment by ioanpocol** [comment]
:+1:

**Comment by petrjasek** [comment]
just wondering if that file `scripts/templates-cache.js` should be there at all, this is generated via grunt task right?

**Comment by vied12** [comment]
Yes it is generated by a grunt task. You mean that you prefer to gitignore it ?

**Comment by petrjasek** [comment]
yes if possible. it should be also part of bower folder so i don't think we need this one

**Comment by vied12** [comment]
Ok but then we need to reconnect the task that generate this file when templates are modified,
because this file is imported in `index.html`

**Comment by petrjasek** [comment]
I see it's not part of `grunt server` task. so then it seems like a bigger task and lets not do it as part of this PR

**Comment by vied12** [comment]
:ok_hand:

Le mar. 27 oct. 2015 à 17:38, Petr Jašek <notifications@github.com> a
écrit :

**Comment by amagdas** [comment]
:+1:

**Comment by ioanpocol** [comment]
Please rebase

**Comment by vied12** [comment]
https://github.com/superdesk/superdesk/pull/1379 includes these changes

**Pull request closed without merging**
