### PR TITLE
[SD-3166] - Use the 'en' dictionary if the language of story is 'en-US' or 'en-AU'

### PR DESCRIPTION
**Pull request by akintolga**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by plamut** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Comment by ioanpocol** [comment]
If there are also en-US and/or en-AU dictionaries, those dictionaries should be used.
I think this case is not covered here (at least in tests)

**Comment by akintolga** [comment]
You are right Ioan, I'll add a test for that case. Thanks.

**Comment by petrjasek** [comment]
looks good, but you might also need to make some changes on backend - in `dictionaries/service` there is `get_model_for_lang` function, it is used for suggestions, so it should use the same logic

**Comment by akintolga** [comment]
I'm closing this PR for the time being, will create another one later.

**Pull request closed without merging**
