### PR TITLE
(imp) Changed pubstatus as per IPTC Standards

### PR DESCRIPTION
**Pull request by sivakuna-aap**
1. Changed pubstatus as per IPTC Standards
2. Refactored aap_mm_datalayer to set auth_cookie only when it is needed.

@mdhaman This PR fixes the comments in https://github.com/superdesk/superdesk/pull/546

### CODE REVIEW

**Comment by mdhaman** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
@superdesk/owners @superdesk/superdesk-australia please review the changes for `pubstatus`

**Comment by akintolga** [comment]
:+1:

**Comment by amagdas** [comment]
:+1:

**Pull request merged**
