### PR TITLE
chore(travis): add e2e profile for firefox

### PR DESCRIPTION
**Pull request by actionless**

### CODE REVIEW

**Comment by amagdas** [comment]
Looks good, no more screenshots?
:+1:

**Comment by actionless** [comment]
@amagdas tokens have very small TTL :(

**Comment by petrjasek** [comment]
it's failing because btn selectors work different in chrome and firefox.
edit `client/app/scripts/superdesk/menu/notifications/views/notifications.html` and change `Sign out` to `SIGN OUT`. it's uppercased now via css

**Comment by actionless** [comment]
@petrjasek  from time to time on travis chrom tests are failing with:
```
Failures:

1) login user can log out

Message:

Expected '' to be Displayed.

Stacktrace:

Error: Expected '' to be Displayed.

2) login user can log out

Message:

Expected '' to be Displayed.

Stacktrace:

Error: Expected '' to be Displayed.

Finished in 75.911 seconds

9 tests, 29 assertions, 2 failures
```

**Comment by petrjasek** [comment]
@actionless will check that, as for this PR I think it's :ok:

**Pull request merged**
