### PR TITLE
feat(multi-content): Multi-content view as a widget on workspace

### PR DESCRIPTION
**Pull request by ioanpocol**

### CODE REVIEW

**Comment by plamut** [comment]
So far so good IMO.

**Comment by petrjasek** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1: (didn't check CSS)

**Comment by plamut** [comment]
So only the template and styling have been updated from the last time (when WIP label was still applied)?

:+1:

**Comment by pavlovicnemanja92** [comment]
Yes, some little changes to html structure and added some new styles for workspace type of widget. Nothing in JS files.

**Pull request merged**
