### PR TITLE
[sd-2604]-(fix) - It is possible to populate numerous scheme rules without saving them

### PR DESCRIPTION
**Pull request by sjunaid**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1: Please add a e2e test

**Comment by mugurrus** [comment]
:+1: with e2e test

**Comment by ioanpocol** [comment]
:+1:  (a unittest will be fine but also an e2e test it's ok)

**Comment by ioanpocol** [comment]
Sorry, I closed by mistake

**Pull request merged**
