### PR TITLE
[SD-3347](fix) Fixing the facets display in global search.

### PR DESCRIPTION
**Pull request by mdhaman**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
is this related to [SD-3347](http://dev.sourcefabric.org/browse/SD-3347)?

**Comment by akintolga** [comment]
Yes it is related, I'll link these two tasks...

**Comment by akintolga** [comment]
:+1:

**Comment by plamut** [comment]
:+1:

**Comment by mdhaman** [comment]
yes. Siva it is related to SD-3347

**Pull request merged**
