### PR TITLE
(feat) Destination Groups

### PR DESCRIPTION
**Pull request by sivakuna-aap**
[SD-1895] UI: Output Channels maintenance screen
[SD-1896] UI: Destination Group maintenance screen

Still some more work pending which is assigned to @eozan

### CODE REVIEW

**Comment by ioanpocol** [comment]
:+1: 
A few e2e tests are required

**Comment by ioanpocol** [comment]
a rebase is needed

**Comment by ioanpocol** [comment]
Please make a rebase on superdesk/destinations

**Comment by sivakuna-aap** [comment]
Rebased both on destinations and master

**Comment by mugurrus** [comment]
please try creating a new branch from master and pick your commits from destinations

**Comment by sivakuna-aap** [comment]
Based on @nidzix suggestion I rebased on master for using new directive for Modal

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
