### PR TITLE
[SD-2490] Make provider a general setting

### PR DESCRIPTION
**Pull request by marwoodandrew**

### CODE REVIEW

**Comment by amagdas** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1: (except 2 behave tests that are failing, the same as for pr #720)

**Comment by marwoodandrew** [comment]
Test failing due to what #722 fixes, I think

**Comment by ioanpocol** [comment]
Yes, the tests are fixed

**Pull request merged**
