### PR TITLE
fix(saved search): Set a larger limit(200) for saved search list

### PR DESCRIPTION
**Pull request by ioanpocol**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
I think 200 was ok but 2000 is more than the required. Is there a real need/requirement for this?

**Comment by ioanpocol** [comment]
There is this issue on saved_search that some saved search are not showed. Seams that currently on systems used for preview there are a lot of saved_searches and I'm not sure if 200 is enough.

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Pull request merged**
