### PR TITLE
fix(client): only enable ng-view when we get user preferences

### PR DESCRIPTION
**Pull request by petrjasek**
this will prevent rendering incomplete pages to users

### CODE REVIEW

**Comment by plamut** [comment]
Wouldn't it be better to resolve this in the router, so that loading the template would wait until user preferences have been fetched? It would be IMO a cleaner solution than communicating through the `$rootScope` and having the template checking for the (non-)existence of the `preferences` object.

(I'm not aware of all the details of the system though, so that might not be possible...)

**Comment by petrjasek** [comment]
it might be, will check.

**Comment by plamut** [comment]
That would be great. Defining a promise to wait for in the router is the way to go, and let's hope there are no big things that would break if we do this change.

**Comment by petrjasek** [comment]
ping @superdesk/developers

**Comment by amagdas** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by plamut** [comment]
Wouldn't it be better to simply add a `resolve`  property?

**Comment by petrjasek** [comment]
@plamut you mean in route registration? that wouldn't stop fetching data in other resolves before user authenticates.

**Comment by plamut** [comment]
Yes, in the route registration, it's cleaner than manually managing and checking on a global flag in root scope. I mean it works, but it's not ideal IMO.

Would it make sense to add some kind of a "has logged in" promise to other resolves? Kind of makes sense if things are not supposed to be loaded before that. But I'm not sure exactly how complicated our routing logic is and how much refactoring would such an improvement require. :)

**Comment by petrjasek** [comment]
problem with that is that it would be just eg:
```
resolve: {auth: auth.promise, users: function(user) { return users.query(); }}
```
but it would be like:
```
resolve: {users: function(auth, users) { return auth.promise.then(function() { return users.query(); }); }
```
so it would be possible, but we would have to update every single resolve.

bth the flag is set on root scope only to be able to display some kind of `loading` indicator that is not there yet, otherwise it would be just local variable in `run` func.

**Comment by plamut** [comment]
I see, it would indeed be verbose, and probably not worth the effort at this point.
Thanks!

**Pull request merged**
