### PR TITLE
[WIP] RSS ingest: extract referenced images' URLs from RSS entries

### PR DESCRIPTION
**Pull request by plamut**
I am adding support for ingesting external images referenced by entries (items) in an RSS feed. The first step is to find all URLs that reference an external image.

Please check the MIME types and the file extensions for the image types we want to support and let me know if anything should be changed. Please also verify that the list of RSS tags we take into account when looking for image URLs is indeed complete.

Thanks!

### CODE REVIEW

**Comment by mugurrus** [comment]
Link element defines the hyperlink to the item, not media content, see: http://www.w3schools.com/webservices/rss_tag_title_link_description_item.asp

Enclosure item is used for media content: http://www.w3schools.com/webservices/rss_tag_enclosure.asp

**Comment by plamut** [comment]
The `feedparser` library places the parsed enclosure tags into the `.links` attribute on the parsed item (along with other links), hence the code that examines this list.

**Comment by mugurrus** [comment]
:+1:

**Comment by plamut** [comment]
Closing this, will issue a new PR with the next part of this feature.

**Pull request closed without merging**
