### PR TITLE
fix(authoring): SD-3103 Fixed unlock button on authoring

### PR DESCRIPTION
**Pull request by pavlovicnemanja92**
SD-3103

### CODE REVIEW

**Comment by ioanpocol** [comment]
:+1: 
At least one e2e test for unlock functionality is needed.

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Comment by pavlovicnemanja92** [comment]
I will add e2e tests for lock/unlock feature in separate PR.

**Pull request merged**
