### PR TITLE
feat(editor): Fixed youtube and Instagram embed code. SDPA-45

### PR DESCRIPTION
**Pull request by eozan**

### CODE REVIEW

**Comment by petrjasek** [comment]
:+1:

**Comment by vied12** [comment]
:ok_hand:

**Comment by ioanpocol** [comment]
Running "jshint:all" (jshint) task

   app/scripts/superdesk/editor/editor.js

   1348 |                    '^((http:\/\/(instagr\.am\/p\/.*|instagram\.com\/p\/.*|www\.instagram\.com\/p\/.*))|(https:\/\/(www\.instagram\.com\/p\/.*)))$'

                                                                                                                                                           ^ Line is too long.

   1323 |                        return (match && match[1].length == 11) ? match[1] : false;

                                                                    ^ Expected '===' and instead saw '=='.

**Comment by vied12** [comment]
@ioanpocol fixed :ambulance:

**Pull request merged**
