### PR TITLE
feat(desks) - Master desk view - Add Users tab

### PR DESCRIPTION
**Pull request by ioanpocol**

### CODE REVIEW

**Comment by amagdas** [comment]
:+1:

**Comment by ioanpocol** [comment]
There were some comments from Nikola that disappear after I performed an amend on commit.
Not fixed yet:
1. on user update refresh the view
2. refactor to use groupBy on finding roles available for a desk
3. when a role for a desk is hide, a small UI alignment issue appear

**Comment by ioanpocol** [comment]
The refresh of view after user change will be added in a different PR

**Comment by nidzix** [comment]
:+1:

**Pull request merged**
