### PR TITLE
[SD-3034] Don't overwrite versions from Reuters and apply cancels as kills

### PR DESCRIPTION
**Pull request by marwoodandrew**
Dependent on superdesk/superdesk-core#125

### CODE REVIEW

**Comment by mdhaman** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Comment by ioanpocol** [comment]
Please rebase and update the dependency to core.

**Comment by pavlovicnemanja** [comment]
Hey @marwoodandrew Windows users have problem with this because Windows doesn't allow `:` in filename.We can't rebase local branches.

**Comment by marwoodandrew** [comment]
@pavlovicnemanja It's a problem for the fixtures file name right? I will change it!

**Comment by pavlovicnemanja** [comment]
@marwoodandrew yep, for fixtures file names.

**Pull request merged**
