### PR TITLE
Missing elasticsearch port for docker-compose-dev

### PR DESCRIPTION
**Pull request by lnogues**
Missing elasticsearch port for docker-compose-dev

### CODE REVIEW

**Comment by thnkloud9** [comment]
:thumbsup:

**Comment by naspeh** [comment]
Do you want to request elasticsearch locally?
Then you probably need the same action for mongodb...

**Comment by lnogues** [comment]
It's always useful for debugging to expose everything

**Comment by naspeh** [comment]
yep, so let's add mongodb port also there

**Comment by naspeh** [comment]
👍

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
