### PR TITLE
Content api

### PR DESCRIPTION
**Pull request by plamut**
Merging updates in master into content-api (a long running topic branch).

Edit: sorry for so many commits, I was a bit in a hurry (should've probably squashed all these "master" commits into a single one).

### CODE REVIEW

**Comment by amagdas** [comment]
I think a rebase is needed instead of merge...

**Comment by plamut** [comment]
The rebase was kind of messy (that's why I wanted to avoid it first after a discussion with @petrjasek ), but in the end I got it through.

Should I simply do a force push now? I've checked with @mugurrus and he's not working on this API branch at the moment, so it should be OK.

**Comment by amagdas** [comment]
Use the force Luke :)

**Comment by plamut** [comment]
Force applied. :smile:

**Comment by plamut** [comment]
Also, I suggest we start rebasing this branch on a more regular basis - but *not* without prior communication with anyone potentially involved, of course.

**Pull request merged**
