### PR TITLE
fix(monitoring): Monitoring show nothing after a saved search is adde…

### PR DESCRIPTION
**Pull request by ioanpocol**
…d to the monitoring view and the the monitoring view is deleted

### CODE REVIEW

**Comment by pavlovicnemanja92** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
Instead of handling it on client side it would have been better if we can delete the saved search from user preferences when a saved search is deleted.

**Comment by ioanpocol** [comment]
@sivakuna-aap Yes, we can do also the changes on saved search delete but I think those changes are needed as a fall off solution.

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
