### PR TITLE
Remove the symbolic link to bower.json. It works now on windows

### PR DESCRIPTION
**Pull request by vied12**
Because @darconny is still using windows :trollface:, we have to keep in mind that symblink doesn’t work on it.
Then I reversed the link and the file to have the real file at the root of the project. Bower won't fail any more on Windows for that.

### CODE REVIEW

**Comment by plamut** [comment]
It seems that this broke the build, `cd client` command fails. :wink: Travis settings need to be updated as well.

**Comment by plamut** [comment]
I think we can consider this build as passed, it's just the coverage that got stuck.

**Comment by amagdas** [comment]
:+1:

**Comment by plamut** [comment]
What's the status of this? Has the symbolic link been re-introduced?
(read something about that somewhere, I think...)

**Comment by petrjasek** [comment]
:+1:

**Comment by ioanpocol** [comment]
A rebase is needed

**Comment by vied12** [comment]
Updated

**Comment by plamut** [comment]
:+1:

**Pull request merged**
