### PR TITLE
Fix (backspace on edit): Fix for chrome

### PR DESCRIPTION
**Pull request by Aca-jov**
SD-2366

### CODE REVIEW

**Comment by plamut** [comment]
:+1:

**Comment by amagdas** [comment]
:+1: Rebase is needed before being able to merge.

**Comment by plamut** [comment]
It's also recommended to add tests (should even be mandatory if you ask me :smile: )

**Comment by petrjasek** [comment]
@plamut right. @Aca-jov you want to do it or shall I?

**Comment by plamut** [comment]
I recommend @Aca-jov does it as a practice. This PR can wait for a little longer, right, it's not a critical fix?

**Comment by petrjasek** [comment]
fine with me, it's minor in jira, it can wait

**Comment by ioanpocol** [comment]
Rebase is needed

**Comment by ioanpocol** [comment]
Two javascript unittests are failing

**Comment by plamut** [comment]
Yes, the `isRendering` variable is declared in a global scome (missing `var`).

https://github.com/Aca-jov/superdesk/blob/editBackspace/client/app/scripts/superdesk/editor/spellcheck/spellcheck.js#L201

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
