### PR TITLE
[sd-1913-2]-(Modifications)-Create related items widget in authoring (ch...

### PR DESCRIPTION
**Pull request by sjunaid**
...anges to consider _created and _updated for creation and updation date)

### CODE REVIEW

**Comment by eozan** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by ioanpocol** [comment]
Failures:

  1) Fetch can fetch from content with menu
   Message:
     [31mNoSuchElementError: No element found using locator: By.cssSelector("[title=\"Copy\"]")[0m
   Stacktrace:
     NoSuchElementError: No element found using locator: By.cssSelector("[title=\"Copy\"]")
==== async task ====
Asynchronous test function: it()
Error
    at /home/travis/build/superdesk/superdesk/client/spec/helpers/content.js:39:22
Error
    at [object Object].<anonymous> (/home/travis/build/superdesk/superdesk/client/spec/fetch_spec.js:107:5)
    at Object.<anonymous> (/home/travis/build/superdesk/superdesk/client/spec/fetch_spec.js:9:1)

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
