### PR TITLE
Update Ubuntu base image to resolve python package resolution issues

### PR DESCRIPTION
**Pull request by ph0bos**

### CODE REVIEW

**Comment by petrjasek** [comment]
hey, not sure how stable is this ubuntu, maybe we should try switching to debian as base image?
ping @superdesk/developers

**Comment by ph0bos** [comment]
It's the latest base image release (using 15.10, released in April), it's not an LTS release but is "stable".

However, happy to try switching to the Debian image, that would resolve the python package issues also.

**Comment by actionless** [comment]
what does it mean "to resolve python package resolution issues"?

**Comment by ph0bos** [comment]
The Python package problem relates to this "unmet dependencies" issue: http://askubuntu.com/questions/275861/problem-installing-python-dev

**Comment by actionless** [comment]
how can it be reproduced here?

**Comment by petrjasek** [comment]
can it be something related to docker cache? just tried to build backend from scratch and seems working

**Comment by ioanpocol** [comment]
What is the status of this PR?

**Comment by ph0bos** [comment]
yes, it would appear that the build is now working. Docker Cache or Ubuntu Apt Repo will have refreshed and resolved the issue.

Can close this.

**Pull request closed without merging**
