### PR TITLE
LBSD-771 Save and use language preference for users in the back-office

### PR DESCRIPTION
**Pull request by vladnicoara**
Allow the user to select a prefered language from the available
translations. As a fallback the browser language it is to be used( if
available)

### CODE REVIEW

**Comment by nistormihai** [comment]
LGTM

**Comment by ioanpocol** [comment]
Small issue:
   spec/helpers/user_prefs.js
     30 |        element(by.css('[name="user_language"]')).element(by.cssContainingText('option', lang)).click()
                                                                                                                ^ Missing semicolon.
     31 |    }
              ^ Missing semicolon.

**Comment by ioanpocol** [comment]
Please rebase

**Comment by ioanpocol** [comment]
please rebase

**Comment by ioanpocol** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
