### PR TITLE
feat(authoring): Added timestamp to aggregate widget items.

### PR DESCRIPTION
**Pull request by eozan**
SD-2199

### CODE REVIEW

**Comment by plamut** [comment]
:+1:

**Comment by ioanpocol** [comment]
One test should be updated
 1) authoring multi content widget can show items grouped by stage
   Message:
     [31mExpected 'a few seconds ago
item1' to be 'item1'.[0m

**Comment by eozan** [comment]
Fixed failing test.

**Comment by plamut** [comment]
(you already have my approval :wink: )

**Comment by amagdas** [comment]
:+1:

**Pull request merged**
