### PR TITLE
Inject lodash before using it

### PR DESCRIPTION
**Pull request by vied12**
If another project uses underscore, some conflicts can append.

At the end it would be better to remove `_` from globals in `client/.jshintrc`

### CODE REVIEW

**Comment by petrjasek** [comment]
with ng-lodash we have lodash imported twice, it might be enough to call somewhere
```
angular.module('superdesk').constant('lodash', _.noConflict());
```
which would require this refactoring, or to start with just `.constant('lodash', _);`

**Comment by plamut** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Comment by vied12** [comment]
Please don't merge, it's not working.
I can't find a place for angular.module('superdesk').constant('lodash', _.noConflict());

**Comment by vied12** [comment]
I think now it's ok :)

**Comment by plamut** [comment]
OK, merge it then (when the build passes that is).

**Comment by vied12** [comment]
Like every time, I can't :trollface: 
I don't have the rights

**Comment by plamut** [comment]
Keep trying, never give up. :trollface:

**Comment by plamut** [comment]
@vied12 For the reference, this hint might help you if you have trouble merging a pull request  yourself - http://bit.ly/IqT6zt

**Comment by vied12** [comment]
haha stop joking, and give me the right ! ;)

**Comment by plamut** [comment]
I can't, don't have sufficient privileges. :)

**Comment by petrjasek** [comment]
@hlmnrmr can do it!

**Pull request merged**
