### PR TITLE
fix(e2e tests): Split e2e tests in multiple suites and rerun failed t…

### PR DESCRIPTION
**Pull request by ioanpocol**
…ests

### CODE REVIEW

**Comment by plamut** [comment]
@ioanpocol What do you mean by the failed tests being re-run? And what happens if a re-run fails, too?

**Comment by ioanpocol** [comment]
If a test fail, all tests from that spec file will be re-run (see: protractor-flake).
If after 3 tries there are still errors, the e2e tests job will stop with fail result.

**Comment by plamut** [comment]
OK, sounds good. :+1:

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
