### PR TITLE
(fix) Authoring: Allow duplicate of item even if the item belongs to another desk.

### PR DESCRIPTION
**Pull request by mdhaman**

### CODE REVIEW

**Comment by plamut** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Comment by plamut** [comment]
Perhaps also add test(s) for the discovered (and now fixed) bugs so that we can be sure they don't appear again in the future.

**Comment by amagdas** [comment]
Merging this as more PR's are coming for this feature(publishing).

**Pull request merged**
