### PR TITLE
chore(bower): put bower files into its own repo

### PR DESCRIPTION
**Pull request by petrjasek**
you can install it now via `bower install superdesk-client`

there is an extra repo https://github.com/superdesk/bower-superdesk-client

does current version work for you? @thnkloud9 @vied12 @nistormihai

if not I can put there files from bower folder (which are removed in this PR) and push this as a new version

### CODE REVIEW

**Comment by amagdas** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Comment by vied12** [comment]
I would prefer to have the distribution files in the same repository as the source, because we need sometimes to use sources (I think about less files that we would like to include)

**Comment by petrjasek** [comment]
ok that's also possible. so `superdesk-templates` will be generated in dist folder instead of app and there will be a copy of it in bower folder, ok @thnkloud9 ?

**Comment by thnkloud9** [comment]
yeah, that sounds ok to me.

**Comment by petrjasek** [comment]
updated, what about now? @thnkloud9 @vied12
btw do you use this repo with `bower` ? should I register it there?

**Comment by petrjasek** [comment]
ping @thnkloud9 @vied12

**Comment by vied12** [comment]
Yes [we use it](https://github.com/superdesk/liveblog/blob/master/client/bower.json#L25) with bower and it would be wonderful to have it directly from bower with the release system !

**Comment by petrjasek** [comment]
ok cool. will register it on bower then

**Comment by amagdas** [comment]
:+1:

**Comment by amagdas** [comment]
Should we merge this?

**Comment by petrjasek** [comment]
I think so

**Pull request merged**
