### PR TITLE
refactor(templates): put item data into `data` dict

### PR DESCRIPTION
**Pull request by petrjasek**
instead of having it all together, keep item data separate
from template metadata

### CODE REVIEW

**Comment by petrjasek** [comment]
+ introduce private templates. user can see always his private templates plus desk templates if there is desk active

**Comment by mugurrus** [comment]
Looks good but tests need to be fixed

**Comment by petrjasek** [comment]
requires https://github.com/superdesk/superdesk-core/pull/93 now

**Comment by mdhaman** [comment]
@petrjasek Nareg raised a ticket [SD-3750](https://dev.sourcefabric.org/browse/SD-3750) couple of days ago in regards to kill template. I had discussion with Lasky about it and he informed that we need only one kill template per content type.

Please let me know if you want to include the changes in your PR? Or you can merge this PR and we handle it in the next sprint?

**Comment by mugurrus** [comment]
:+1:

**Comment by ioanpocol** [comment]
:+1:

**Comment by petrjasek** [comment]
@mdhaman next sprint it seems :smile:

**Pull request merged**
