### PR TITLE
Fix/translation path

### PR DESCRIPTION
**Pull request by vladnicoara**

### CODE REVIEW

**Comment by vladnicoara** [comment]
Requires this to pass the tests https://github.com/superdesk/superdesk-client-core/pull/32

**Comment by vied12** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Comment by petrjasek** [comment]
without that `de` string you will have to update some e2e tests testing language picker..

**Comment by vladnicoara** [comment]
@petrjasek that is why I mentioned that it needs this https://github.com/superdesk/superdesk-client-core/pull/32 to pass the tests. The file with the 'de' string moved into the superesk-clien-core repo. 
Locally it passes that test without issues. I'll check again

**Comment by petrjasek** [comment]
ah right sorry @vladnicoara my bad
can you maybe update the client reference then? it should pass right?

**Comment by vladnicoara** [comment]
@petrjasek right, I missed that :) rebased now. It should pass now here as well. Thanks!

**Pull request merged**
