### PR TITLE
[SDNTB-201] Modify NITF parser to be able to ingest NTB metadata

### PR DESCRIPTION
**Pull request by jerome-poisson**
NTB specific data mapping is done in settings, following the refactoring
of nitf parser

SDNTB-201

### CODE REVIEW

**Comment by petrjasek** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Comment by petrjasek** [comment]
would be good to have some unittest parsing a sample file

**Comment by jerome-poisson** [comment]
@petrjasek right, I'll add some

**Comment by jerome-poisson** [comment]
The tests are added, are working locally, but can't work here until https://github.com/superdesk/superdesk-core/pull/384 is merged on superdesk-core.

**Pull request merged**
