### PR TITLE
auth.js: use require.toUrl to set the reset password template

### PR DESCRIPTION
**Pull request by vied12**

### CODE REVIEW

**Comment by plamut** [comment]
:+1:

**Comment by ioanpocol** [comment]
One unittest is failing:
PhantomJS 1.9.8 (Linux) auth can use routes with auth=false without identity FAILED

**Comment by plamut** [comment]
Yeah, unexpected GET request due to the changed template URL, the latter now includes the full path (starting from `/base/app...`).

**Comment by vied12** [comment]
I would like to use `superdesk.asset` but at this point the `config` isn't set...
Do you have any clue ?

**Pull request closed without merging**
