### PR TITLE
(fix) Fixing code where the app_initialize allows to insert new documents.

### PR DESCRIPTION
**Pull request by mdhaman**
- Fix to update the master.dev with new vocaburlaries.

### CODE REVIEW

**Comment by akintolga** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by plamut** [comment]
I would consider adding a test, too.

:+1:

**Comment by mdhaman** [comment]
@plamut  agree with testing. I push the code for today's show and tell and created a ticket as well https://dev.sourcefabric.org/browse/SD-3149

**Comment by plamut** [comment]
Since it represents a blocker for development it makes sense to merge it - the immediate value and importance of that are higher than the long term value the test would bring, thus it's fine to add it in a separate PR.

**Pull request merged**
