### PR TITLE
packages - add liveblog extensibility point

### PR DESCRIPTION
**Pull request by amagdas**

### CODE REVIEW

**Comment by amagdas** [comment]
@ancafarcas This is the one :smile_cat:

**Comment by petrjasek** [comment]
just wondering - why do we this linked in packages field?

**Comment by amagdas** [comment]
We need to show if an item is part of a package or not, this is to be easily available, in some designs/stories is to be shown on each item.
We can do it like the current implementation or check on each fetch action, I think the current implementation is more efficient...

**Comment by petrjasek** [comment]
I was thinking if we have to have this `linked_in_packages` given that we can search by `groups.refs.residRef` if that would be properly mapped..

**Comment by amagdas** [comment]
We can search, but as I said, that would mean for each item fetch from archive to do this search and this will hit on performance quite a bit...

**Comment by petrjasek** [comment]
I see didn't realise we do it in a loop :+1:

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
