### PR TITLE
SDPA-111 Fix placeholder text.

### PR DESCRIPTION
**Pull request by naomiaro**
Just fixes a typo.

### CODE REVIEW

**Comment by hlmnrmr** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Comment by naomiaro** [comment]
I meant to merge the other one before commiting this text centering... should I revert that commit and open it in a new branch?

**Comment by petrjasek** [comment]
:+1:
@naomiaro that's fine both are quite small

**Comment by naomiaro** [comment]
@petrjasek OK cool, who usually closes the pull requests?

**Comment by petrjasek** [comment]
anyone

**Pull request merged**
