### PR TITLE
fix(fixture filenames) Windows did not like the colons in the fixture file names

### PR DESCRIPTION
**Pull request by pavlovicnemanja**
Fixed styling issue, closed PR #1638 and opened this one

### CODE REVIEW

**Comment by marwoodandrew** [comment]
@pavlovicnemanja Thanks for fixing that. I was in a hurry to get it done before leaving for the day!

**Comment by pavlovicnemanja** [comment]
hey @marwoodandrew no problem! :)

**Comment by ioanpocol** [comment]
:+1:

**Comment by Aca-jov** [comment]
:+1:

**Pull request merged**
