### PR TITLE
Monitoring widget refreshes on item update

### PR DESCRIPTION
**Pull request by Aca-jov**
SD-3600

### CODE REVIEW

**Comment by petrjasek** [comment]
why should it refresh whole list on lock/unlock?

**Comment by Aca-jov** [comment]
Yes, it should refresh only locked item, i will change.

**Comment by Aca-jov** [comment]
It's changed.

**Comment by ioanpocol** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
