### PR TITLE
[SD-3760] Revisit ingest providers conversion of preformatted to html

### PR DESCRIPTION
**Pull request by marwoodandrew**
See PR superdesk/superdesk-core#107 

This removes the references to the configure defunct feed services and adds references to configure the new parsers.

### CODE REVIEW

**Comment by mugurrus** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1: For now, optional `Feed Parser` will help setting up the RSS provider.

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by actionless** [comment]
:+1:

**Pull request merged**
