### PR TITLE
[sd-3525]-(fix) - Spell check always turned on when opening the editor

### PR DESCRIPTION
**Pull request by sjunaid**

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Comment by plamut** [comment]
:+1:

**Comment by ioanpocol** [comment]
PR https://github.com/superdesk/superdesk/pull/1408 has fixed the e2e tests problems.
Please rebase.

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
