### PR TITLE
[SD-3163] Dont show the publish button if the item state is draft

### PR DESCRIPTION
**Pull request by marwoodandrew**
Attempts to publish anything in a draft state fails the state transition checks, this should avoid that.

### CODE REVIEW

**Comment by sivakuna-aap** [comment]
Can we drive it via authoring.itemActions() similar to other buttons?
https://github.com/superdesk/superdesk/blob/master/client/app/scripts/superdesk-authoring/authoring.js#L501

**Comment by marwoodandrew** [comment]
Other than I tried that and it failed, I look at it again!

**Comment by sivakuna-aap** [comment]
:+1:

**Comment by akintolga** [comment]
:+1:

**Comment by mdhaman** [comment]
:+1:

**Pull request merged**
