### PR TITLE
(fix) [SD-3198] Items open for correct or kill are missing a button to proceed

### PR DESCRIPTION
**Pull request by sivakuna-aap**

### CODE REVIEW

**Comment by mdhaman** [comment]
:+1:

**Comment by plamut** [comment]
:+1:

**Comment by sivakuna-aap** [comment]
@superdesk/developers feedback?

**Comment by akintolga** [comment]
:+1:

**Comment by plamut** [comment]
Just a suggestion - when reviewing WIP pull requests, it is sometimes difficult to review the updates if everything is included in a single commit. I would suggest either grouping work into multiple logical commits, or posting a comment explaining what has been updated (unless it's some trivial change).

This will make it easier to come back later and review only the updates, without having to go through all the code again (esp. useful for larger PRs).

Thoughts on this?

**Comment by sivakuna-aap** [comment]
@plamut I agree. It should be a different commit instead of single commit.

**Pull request merged**
