### PR TITLE
feat(monitoring): Improved show/hide list view on monitoring view

### PR DESCRIPTION
**Pull request by pavlovicnemanja92**

### CODE REVIEW

**Comment by plamut** [comment]
Looks good in general, but ...

(I'll let the reader finish the sentence as an exercise :laughing:  )

:+1:

**Comment by pavlovicnemanja92** [comment]
Tests for this are added in previously PR :-) This is just small inprovement. :-)

**Comment by plamut** [comment]
Ah, so this code is already covered by tests? Good then!

**Comment by ioanpocol** [comment]
:+1:

**Pull request merged**
