### PR TITLE
chore(ci): enable eslint checks

### PR DESCRIPTION
**Pull request by petrjasek**
so far it's for spec files and config files, apps will need some more work.

### CODE REVIEW

**Comment by plamut** [comment]
What's the max line length set to? I have a feeling it's still a bit long, making it sometimes more difficult to review PRs (due to the need for horizontal scrolling), as well as for developing if you work with multiple (narrower) windows side-by-side and you don't have a huge monitor at your disposal.

**Comment by petrjasek** [comment]
I've set it to 111 so now it should fit in github review box

**Comment by plamut** [comment]
Let's hope so. :wink:

**Comment by petrjasek** [comment]
I've done the math :smile:

**Comment by akintolga** [comment]
:+1:

**Pull request merged**
