### PR TITLE
fix e2e failures in bamboo

### PR DESCRIPTION
**Pull request by actionless**
- reporting was broken
 - animations happens slower/faster

### CODE REVIEW

**Comment by actionless** [comment]
junit and screenshot reporters are fixed by now.
now with screenshots i hope it will be easier to debug remaining test failures

**Comment by actionless** [comment]
now all e2e seems to pass on bamboo, at the day time i gonna clean up and then squash it

**Comment by amagdas** [comment]
:+1:

**Comment by mugurrus** [comment]
:+1:

**Pull request merged**
