### PR TITLE
(imp) [SD-1884] Refactor Fetch Endpoints

### PR DESCRIPTION
**Pull request by sivakuna-aap**

### CODE REVIEW

**Comment by ioanpocol** [comment]
Failing scenarios:
features/content_move.feature:4 Send Content from personal to another desk
features/content_move.feature:28 Send Content from one desk to another desk

**Comment by sivakuna-aap** [comment]
Unable to reproduce the exception locally. Fixed it and the build passes.

**Comment by ioanpocol** [comment]
Looks like now it is ok

**Comment by ioanpocol** [comment]
:+1:

**Comment by petrjasek** [comment]
:+1:

**Pull request merged**
