### PR TITLE
Use develop deps on server

### PR DESCRIPTION
**Pull request by pablopunk**
notice is for branch `ansa-develop`

### CODE REVIEW

**Comment by petrjasek** [comment]
why we need this?

**Comment by pablopunk** [comment]
@petrjasek well this branch is `ansa-develop` and those deps are not updated to the latest develop changes. Also, I'm trying to get [SDANSA-422](https://dev.sourcefabric.org/browse/SDANSA-422) tested by QA on an ansa instance so this could do it, but there's some issue in the deployment

**Comment by petrjasek** [comment]
I see, I think that should be already available on sd-ansa, imo we should rather drop this branch

**Comment by pablopunk** [comment]
@petrjasek sure if we don't need it go ahead

**Pull request closed without merging**
